---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUdSUMOij0vCiulNYRPDdryZzlvzUwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTIwMjIxNzAwWhcNMjQxMTE4MjIxNzAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ALl9fUrb8VO25kqXuMUvtmonqFDtquNKdlfNt+l+lsk3c5b4PaLHEL/1Tz+ecg42
    C/TAc4d/c9vDkD0RfPzHcUAaUcp00RaPNBoGPzJgzbQOmHcA3oW3/zeZWCOQ5LnV
    LDt0rIRKCC/n9BCIuX9Lj7WxFW7a74SLNNr2eYzLZFELDEklsZm8oDCuvP2ayI15
    PPWXqWj9Szx5urauy8W0X4sYk7xPIaBknm6IZUiuCXDRw6DQHt/zq1qvz4bFQMN+
    WxpXdBE4C41jkCTYxW2LGas1fqL52u5PZSNnU/bwngZY+280gAxRpXkkm1XnbYXp
    TDS+cadoZHqDEg/nAaBK40Ufi5BMP11KF0EvC82v3v/8Fvmc5uAaRrjQILN9Ioke
    v/lgw/k6ZMIRCmexkcR6y7aSrG6iUWVAxC/BsgREo7+kUI4XxRfBhiwqg8gYCHrQ
    4/8i7XWB9IjzcEuE78R5+3etTLtpf+IHMwOCeAp7xrzpTr1/jZiiFA5O2EPXnPx5
    PIRkEs7eQnKpaleogBy9SrgU00bppAETg9LuvgEGxXAWF3UYr2izRO18+pDP9149
    sfdJ1EZWJBvoHhv0EuCqbcSBw8wRnnGZK7loHPyCs/shulaB9Q608nJB1BhBynbF
    CKL6DPHitEO4+wAOBClQASMCCEDfOiK9jdoyDRPBg/N9AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTDT3IxFStgx6wX
    775YDg0Ca5aK0TANBgkqhkiG9w0BAQ0FAAOCAgEAfoXxniQpyjukOOnRfLwPF/34
    T4SlIL3OwsmRhS84JaLtyMP2VQrMbpdW06Fws+WfcffflPIKPmri2IFmIerzxiG2
    o2rJ3tXtIlA9fq9erpICkrFmR6sXyNUxHxr8RbEGdFwunI5d2j0G2abq+rCaavLa
    f+L2YSatGWJl7SYwymbsX+bzpjdz83tr6SkfHwfTMC6cjVOOQMJYPyU3P8/C95N5
    AgTmk0pOaNimw82ltI7VYCTzouXH/bDL8ExKUVEZTmY1orTOKKPqh/nnz3Xs4yLV
    tRrYRW9dplUnBNVUJPDAAQP9UCI/cauJmuoNEsvx4A1tkP6Kc6iD7JTypqbZF/W/
    3GOmpHmyiajUA+Ii4FmrzKAZpP3M5WPA0/LcYIOd0UQ4Mnq4Ic/RyATc5P/KW/il
    MJoiFNs2asfnvXphCOhtJz0nXliYUe6AF3MDpVJTbuQp6Uu/4VNZN6G9aLBXrRah
    KaH0TlP3TRRV3Z8F8KwYabAWTtGATDDXmzKGP+p/V4zGIe/j1quImQ4O67Fwxloa
    3y3QwKJQ/YHnPqjYHtAPBPbBOBbVz0UT7I6E5rp79hTUyn+qr56pIL2pCQaX0Frd
    xRn6Xrix0vGX09F9Y3/VhJ9hIm40UcBwvNgOQG0lqE5IglmYZrW7Fdfsl4Fly71G
    TYYJ9gZx/bk+6WfNPfw=
    -----END CERTIFICATE-----
    
